repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.0.0.9027
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=mlr_style]
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    -   id: roxygenize
    -   id: use-tidy-description
    #-   id: codemeta-description-updated
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
