# OS ---------------------------------------------------------------------------
os: linux
dist: bionic

# meta -------------------------------------------------------------------------
language: r
cache: packages
latex: false
r_packages:
  - lintr

# Stages -----------------------------------------------------------------------

script: Rscript -e 'lintr::lint_package()'
