# OS ---------------------------------------------------------------------------
os: linux
dist: bionic

# meta -------------------------------------------------------------------------
language: r
cache: packages
latex: false

# Stages -----------------------------------------------------------------------

install: true
script:
  - install.packages("lintr")
  - Rscript -e 'lintr::lint_package()'
